screen:
  width: 1024
  height: 768

grid:
  dim_grille: [5,7,2]
  force_full: False

camera:
  cam_area: [[370,180], [1410,1000]]
  cam_number:  0
  refresh_rate: 1 # refresh each X frames

button:
  hand_area_1: [[400, 920], [500, 1000]]
  hand_area_2: [[200, 10], [300, 80]]

  hand_area_3: [[350, 50], [400, 150]]
  hand_area_4: [[350, 275], [400, 375]]
  hand_area_5: [[350, 525], [400, 625]]
  hand_area_6: [[350, 800], [400, 900]]
  hand_area_7: [[600, 900], [650, 1000]]
  hand_area_8: [[50, 850], [100, 950]]


  # increase if buttons trigger for nothing
  hand_threshold_1: 150 # area (pxl*pxl) 100int
  hand_threshold_2: 150 # area (pxl*pxl)100 int

  cooldown: 4


brick:
  min_brick_size: 500.0 # pxl area
  max_brick_size: 2000_000.0 # pxl area

program:
  swap: False # swap between display panels or show both
  swap_time: 4
  test_model: True
  text_color: [1, 1, 1] # rgb normalized

color:
  # hue: name
  -1: "Air"
  60: "Yellow"
  340: "Magenta"
  200: "Cyan"
  35: "Orange"
  0: "Red"
  80: "Green"

color_mat:
  # name: [conductivity, capacity, density, r_corrosion, max_stress_compre, T_max_service]
  #        W/(m*K),      J/(kg/K), kg/m^3 , no unit    , MPa              ,    K
  "Air":     [0.1, 1000, 1.25, 0, 0, 0]
  "Blue":    [0.5, 850, 600, .8, 1, 1500]
  "Yellow":  [17, 818, 600, .4, 17.7, 1973]
  "Magenta": [6, 1300, 600, .6, 5.5, 1673]
  "Cyan":    [0.5, 850, 600, .8, 1, 1500]
  "Orange":  [10.0, 2000, 600, .9, 0, 0]
  "Red":     [6, 1300, 600, .6, 5.5, 1673]
  "Green":   [60, 1030, 600, .9, 7.86, 1900]
  "Steel":   [20.0, 2000, 600, 1, 0, 0]
  "Molten Steel":   [20.0, 500, 600, 1, 0, 0]

steel:
  temperature: 1873 # K
  cooling: False
  cooling_factor: 0.01 # K/s
